export enum UserRole {
  GUEST = 'GUEST',
  USER = 'USER',
  ADMIN = 'ADMIN',
}

export enum TripStatus {
  PLANNING = 'PLANNING',
  CONFIRMED = 'CONFIRMED',
  ONGOING = 'ONGOING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum TravelStyle {
  BUDGET = 'BUDGET',
  STANDARD = 'STANDARD',
  LUXURY = 'LUXURY',
  ADVENTURE = 'ADVENTURE',
  FAMILY = 'FAMILY',
  COUPLE = 'COUPLE',
  SOLO = 'SOLO',
  BUSINESS = 'BUSINESS',
}

export enum BookingType {
  FLIGHT = 'FLIGHT',
  HOTEL = 'HOTEL',
  TRAIN = 'TRAIN',
  BUS = 'BUS',
  ACTIVITY = 'ACTIVITY',
  CAR_RENTAL = 'CAR_RENTAL',
}

export enum BookingStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
}

export enum ExpenseCategory {
  TRANSPORTATION = 'TRANSPORTATION',
  ACCOMMODATION = 'ACCOMMODATION',
  FOOD = 'FOOD',
  ACTIVITIES = 'ACTIVITIES',
  SHOPPING = 'SHOPPING',
  EMERGENCY = 'EMERGENCY',
  OTHER = 'OTHER',
}

export enum NotificationType {
  TRIP_ALERT = 'TRIP_ALERT',
  BOOKING_REMINDER = 'BOOKING_REMINDER',
  ITINERARY_ACTIVITY = 'ITINERARY_ACTIVITY',
  BUDGET_THRESHOLD = 'BUDGET_THRESHOLD',
  TRIP_COMPLETION = 'TRIP_COMPLETION',
  SYSTEM = 'SYSTEM',
}

export enum ReviewStatus {
  APPROVED = 'APPROVED',
  PENDING = 'PENDING',
  REJECTED = 'REJECTED',
}

export enum ActivityType {
  TRANSIT = 'TRANSIT',
  CHECKIN = 'CHECKIN',
  SIGHTSEEING = 'SIGHTSEEING',
  DINING = 'DINING',
  ACTIVITY = 'ACTIVITY',
  RELAXATION = 'RELAXATION',
  SHOPPING = 'SHOPPING',
  OTHER = 'OTHER',
}
